'use client';
// import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import {Layout, Flex, Menu} from 'antd';
import { useStyles } from "./layout-style";
import NavBar from "@/components/top-navbar";
import Poll from "@/components/poll";

const {Header, Footer, Sider, Content} = Layout;

const inter = Inter({ subsets: ["latin"] });

/*export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};*/

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {

  const {styles} = useStyles();
  return (
    <html lang="en">
      <body className={inter.className}>
          <Flex gap="middle" wrap="wrap"> 
            <Layout className={styles.layoutStyle}>
              <Header className={styles.headerStyle}><NavBar/></Header>
              <Layout>
                <Content className={styles.contentStyle}>
                  {children}
                </Content>
                
                <Sider width="25%" className={styles.siderStyle}>
                    <Poll/>
                </Sider>
              </Layout>
              <Footer className={styles.footerStyle}>Footer</Footer>
            </Layout>
        </Flex>
      </body>
    </html>
  );
}
